### ISSUE TITLE
Support for extracting title information from an incoming web hook using Terraform

### ISSUE THREAD

**Issue by peter-hippo** [BetterStackHQ/terraform-provider-better-uptime#108]
I noticed that it's possible to extract information from an incoming web hook to update the title of the created incident. This is really great since it will make it more clear what caused the trigger. But I could not find it inside the Terraform provider documentation, that is how to configure this setting using code. While browsing the API documentation here https://betterstack.com/docs/uptime/api/incoming-webhooks-response-params I also could not find it. 

![Screenshot 2024-07-05 at 11 11 28](https://github.com/BetterStackHQ/terraform-provider-better-uptime/assets/128389589/e2ac34ae-7b5b-4070-b6aa-7b6c90e35113)

It would be great if this was also supported by the Terraform provider or at least provided in the API docs so I could implement a PR for this feature!

:rocket:

**Comment by PetrHeinz** [comment]
Hello @peter-hippo, thanks for reporting this! 🙌 

I've added the support in both API and Terraform into our roadmap. In the meantime, you should be able to add the title extraction in the GUI at least, and subsequent API updates should not affect it.

**Comment by peter-hippo** [comment]
Thanks @PetrHeinz , appreciate it! 👏

**Comment by PetrHeinz** [comment]
Hi @peter-hippo, just wanted to send you a quick update that it's now possible to set `title_field` in a similar way to `cause_field` in IncomingWebhooks in [v0.11.8](https://github.com/BetterStackHQ/terraform-provider-better-uptime/releases/tag/v0.11.8) 🚀 

It's been also added to the API: https://betterstack.com/docs/uptime/api/incoming-webhooks-response-params/

Thanks for reaching out about the missing piece 🙌
