### ISSUE TITLE
Add signing key to OpenTofu registry

### ISSUE THREAD

**Issue by nihaals** [BetterStackHQ/terraform-provider-better-uptime#116]
This provider is missing signing keys in the OpenTofu registry, so validation is currently skipped:
> Installed betterstackhq/better-uptime v0.11.9. Signature validation was skipped due to the registry not containing GPG keys for this provider

Provider keys can be submitted at the [GitHub repo](https://github.com/opentofu/registry/issues/new?labels=provider-key%2Csubmission&template=provider_key.yml&title=Provider+Key%3A+).

**Comment by PetrHeinz** [comment]
Hi @nihaals,

Thank you for your patience on this one 🙌 

I've submitted the public key to OpenTofu registry: https://github.com/opentofu/registry/issues/1155

The PR was already merged, would you be so kind to test whether this resolved the issue with validation being skipped? 🙏 

Thanks, and have an amazing day!

**Comment by nihaals** [comment]
It looks like it's working, thanks!

**Comment by PetrHeinz** [comment]
Amazing! Happy to hear that, @nihaals 🚀
