### ISSUE TITLE
Statuspage top navigation links

### ISSUE THREAD

**Issue by Rogdham** [BetterStackHQ/terraform-provider-better-uptime#120]
Hello, I'm interested with configuring these values (statuspage advanced settings) in terraform:

![screenshot-2024-10-15-13:48:40](https://github.com/user-attachments/assets/f21abda5-a25a-44a2-ab11-f96c6cae82d6)

I did not find them in [the documentation about `betteruptime_status_page` resource](https://registry.terraform.io/providers/BetterStackHQ/better-uptime/latest/docs/resources/betteruptime_status_page), did I miss anything?

Thank you!

**Comment by PetrHeinz** [comment]
Hi @Rogdham,

Thanks for reaching out about this! 🙌 

You're right that it's not currently possible to configure top navigation links replacements via Terraform. I've added this into our roadmap, but I can't really provide any ETA. We'll make sure to update this issue when we make progress on it 🙏 

As a workaround, you can configure these values manually in Web GUI after creating a Status Page via Terraform. Subsequent Terraform updates should not modify the settings at all, keeping what you've set up in the GUI.

**Comment by LukBrezina** [comment]
Hi @Rogdham , it should be now possible to update the links in the version [v0.12.2](https://github.com/BetterStackHQ/terraform-provider-better-uptime/releases/tag/v0.12.2) 

Feel free to give it a try! 🙌

**Comment by Rogdham** [comment]
Works as expected with new version. Thanks!
