### ISSUE TITLE
Outgoing incident webhook

### ISSUE THREAD

**Issue by carlo-quinonez** [BetterStackHQ/terraform-provider-better-uptime#121]
Can an outgoing incident webhook created using terraform? I dont even see an API for outgoing webhooks.

**Comment by gyfis** [comment]
Hey @carlo-quinonez, we don't currently have API support for outgoing webhooks at Better Stack.

Thanks for the suggestion though! Can you share a bit more about your use case? That'd help me a lot in understanding what you're trying to achieve. Thanks!

**Comment by carlo-quinonez** [comment]
Our team supports products built on top of microservice with and a datamesh. Consequently, there's a lot of separate pieces of infrastructure to monitor. We settled on:
- Single public status page. Each product is represented by a single incoming webhook
- Separate internal status pages, one internal page per product we support. Engineers can go nuts with monitors, heartbeats, and webhooks.
- A custom "incident handler" to bridge the internal and external status pages. Routes incidents to the correct public monitor using the metadata associated with the incident and related monitor. 

![image](https://github.com/user-attachments/assets/9e1f0690-6e3e-4ad3-8266-b3b6a575f5fd)

**Comment by gyfis** [comment]
Thanks @carlo-quinonez, that's very helpful! We'll take a look at the outgoing webhooks API and I'll get back to you when I have an update. Do you have a timeline for this project that you'd like to hit?

**Comment by carlo-quinonez** [comment]
The project is already late, fortunately this isn’t a blocker since I can create the webhook manually in the betterstack backend UI and mention this issue in the README for the terraform 

That said, I’m working on the code for the incident handler this sprint and I hope to merge all the work by Nov 6…

**Comment by iatanas0v** [comment]
Hey @carlo-quinonez :wave: 

We released `v0.12.0` of our BetterStackHQ Terraform provider just yesterday  and it includes the option to manage outgoing webhooks https://registry.terraform.io/providers/BetterStackHQ/better-uptime/latest/docs/resources/betteruptime_outgoing_webhook. Hope this would solve your use case :crossed_fingers:

**Comment by carlo-quinonez** [comment]
🙏🏽
