### ISSUE TITLE
betteruptime_monitor request_headers doesn't add header

### ISSUE THREAD

**Issue by Toilal** [BetterStackHQ/terraform-provider-better-uptime#19]
I try to set request headers, but it doesn't work.

```
resource "betteruptime_monitor" "api_graphql" {
  url              = "https://${var.ecs_subdomain_name}.${data.cloudflare_zone.default.name}"
  monitor_group_id = local.betteruptime.betteruptime_monitor_group_id
  monitor_type     = "status"
  http_method      = "POST"
  request_body     = jsonencode({query="query {authenticated}"})
  request_headers = [{Content-Type = "application/json"}]
}
```

Monitor is created, but no request header is defined.

**Comment by Toilal** [comment]
After reading monitor API docs, I found the right syntax

```terraform
  request_headers = [{name = "Content-Type", value = "application/json"}]
```

That beeing said, API could check input data structure and error instead of silently omiting the request headers.

**Comment by adikus** [comment]
@Toilal Thanks for the the PR! I've merged it into master. 
We'll have to discuss internally about the the API erroring out in this use case, since ignoring unknown attributes is currently our preferred default behaviour.
