### ISSUE TITLE
Terraform provider does not update monitor paused status

### ISSUE THREAD

**Issue by redzioch** [BetterStackHQ/terraform-provider-better-uptime#25]
Version:

```
$ terraform version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/betterstackhq/better-uptime v0.3.10
```

Steps to reproduce:

1. Create monitor with `paused = false`

```
resource "betteruptime_monitor" "bu_monitor" {
  url = "http://..."
  paused = false
  ...
}
```

2. Run `terraform apply` and confirm changes.

3. Change `paused` to `true`:

```
resource "betteruptime_monitor" "bu_monitor" {
  url = "http://..."
  paused = true
  ...
}
```

4. Run again `terraform apply` and confirm changes.

5. Run `terraform plan/apply` to see that paused status is not changed and Terraform wants to change it again.

**Comment by adikus** [comment]
@redzioch Thanks for reporting! Looks like our API doesn't return the `paused` attribute that our provider plugin expects (instead we have `paused_at`). I'll get that added in.

**Comment by adikus** [comment]
@redzioch The change is now live. It's now reporting for that my monitor is paused correctly.

**Comment by redzioch** [comment]
Works, thanks!
