### ISSUE TITLE
Missing ability to show history graphs

### ISSUE THREAD

**Issue by itsmatteomanf** [BetterStackHQ/terraform-provider-better-uptime#26]
In the `betteruptime_status_page_resource` resource there is the ability to show history via the `history` boolean.

This is missing the ability, present in the GUI, to show the latency graph, which is very useful.

**Comment by adikus** [comment]
Hi @itsmatteomanf! Thanks for reporting!

Looks like we added in only on the status page resource, but forgot about the resources. I'll make sure we add it there as well.

**Comment by adikus** [comment]
@itsmatteomanf Sorry about dropping the ball on this one! I've finally created a PR on this and will release it soon.
