### ISSUE TITLE
Auth values always shows up as a change

### ISSUE THREAD

**Issue by leetrout** [BetterStackHQ/terraform-provider-better-uptime#29]
Hey 👋 

Auth values are always showing up as changed...

```
# betteruptime_monitor.betteruptime_monitor_foo will be updated in-place
  ~ resource "betteruptime_monitor" "betteruptime_monitor_foo" {
      + auth_password         = (sensitive value)
      + auth_username         = (sensitive value)
        id                    = "1234"
        # (23 unchanged attributes hidden)
    }
```

My version:

```
$ terraform version
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/betterstackhq/better-uptime v0.3.12
```

**Comment by theaccordance** [comment]
Not sure if you're still having the issue or not, from my experience I'm not having that issue, but I am using a variable to pass in the value instead of hard coding it into my commit.  

FWIW, I'm using 1Password as the source of truth for my creds, I can combine their CLI with terraforms to pipe the value to TF

**Comment by leetrout** [comment]
> Not sure if you're still having the issue or not, from my experience I'm not having that issue, but I am using a variable to pass in the value instead of hard coding it into my commit.

We removed all monitors from terraform and are only using it for heartbeats. But it is something they should be able to fix by adding a `DiffSuppressFunc` to check for empty values.

I didn't want to spend time writing up the PR if they wouldn't accept it so I opened the issue to see if there was any traction.

**Comment by gyfis** [comment]
@leetrout Hi Lee, thanks for raising the issue! I tested a simple terraform recipe and I'm not seeing the issue you described. Can you provide a reproducible example of a monitor resource that would show the update for the `auth_username` and `auth_password`, please? I'll close the issue, but happy to reopen once we can reproduce. Thanks again!

FWIW here's the monitor resource I tested the auth attributes on:

```terraform
resource "betteruptime_monitor" "this" {
  url          = "https://example.com"
  monitor_type = "status"
  auth_password = "abcd"
  auth_username = "efgh"
}
```
