### ISSUE TITLE
Monitor_type not accepting values in Terraform

### ISSUE THREAD

**Issue by chrisreeves-** [BetterStackHQ/terraform-provider-better-uptime#33]
### Example Terraform

resource "betteruptime_monitor" "betteruptime" {
monitor_type = "tcp"
port = "3128"
url = "test.example.com"
pronounceable_name = "The service name example"
recovery_period = "180"
check_frequency = "60"
regions = ["us", "eu", "au"]
ssl_expiration = "30"
domain_expiration  = "30"
}

### Error Message

`Error: PATCH https://betteruptime.com/api/v2/monitors/835996 returned 422: {"errors": {"monitor_type":["is invalid. Valid values are: status, expected_status_code, keyword,keyword_absence"]}}`

### Expected Behaviour

Adds a monitor pointing to `test.example.com:3128`

**Comment by gyfis** [comment]
Hi @chrisreeves, thanks for the report! This is the expected behavior at the moment - you can't change the monitor type from a http-based type to a tcp-based type after it was already created. Do you mind sharing a bit more about your use-case here? Thanks!

**Comment by chrisreeves-** [comment]
Ah yes, thanks @gyfis I found by removing it and adding a fresh new TCP check it worked.
This was just a problem during deployment and no use case to switch between an HTTP and TCP is needed.
