### ISSUE TITLE
Invalid region sent when state mismatch

### ISSUE THREAD

**Issue by rahulpsd18** [BetterStackHQ/terraform-provider-better-uptime#37]
After creating a monitor resource, if the monitor is updated from the betteruptime dashboard, the next deployments start failing with error:
```
Error: PATCH https://betteruptime.com/api/v2/monitors/[MONITOR_ID] returned 422: {"errors":{"regions":["are not included in the list: us, eu, as, au"]}}
```

This can be replicated following the steps:
1. Create a monitor 
   ```terraform
   resource "betteruptime_monitor" "this" {
     url          = "https://example.com"
     monitor_type = "status"
   }
   ```
   This creates a monitor with `regions: null`. Which is perfectly fine.
   Deploying this multiple times works fine.
2. Now open your betteruptime dashboard and update "On call escalation" (region is not updated):

    <img src="https://user-images.githubusercontent.com/14837582/202434110-49d931e0-56ca-4c48-b4c7-6d13999b4b02.png" height="150" /> 
4. Now deployment starts failing with aforementioned error.
5. The `tf plan` shows the following change:
    ```
    ~ resource "betteruptime_monitor" "this" {
        ~ regions = [
              - "us",
              - "eu",
              - "as",
              - "au",
          ]
          ... // truncated
      }
    ```
6. I assume `regions: []` is being sent in the PATCH HTTP call, which fails with 422 from betteruptime (as verified with Postman).
7. It should be `regions: null` in the Patch HTTP call. Even if we want this to fail, a user friendly message would be of greater help than a 422 error.

---

The error here is HTTP Patch call being sent with `regions: []`, which is not accepted by betteruptime and fails with 422.
It should either be a valid region array with atleast 1 region OR `null`.

**Comment by adikus** [comment]
Thanks for the issue and thorough description @rahulpsd18!
We'll have a look into fixing this.

**Comment by gyfis** [comment]
@rahulpsd18 Thanks again for opening the issue. I looked into it, and based on the open issues in Terraform, I wasn't able to figure out a good enough fix for this one.

- I wanted to use the `DiffSupressFunc` first, to ignore if the original regions is an empty list or nil, however the `DiffSupressFunc` doesn't work for `schema.TypeList` https://github.com/hashicorp/terraform-plugin-sdk/issues/477
- Then I wanted to add the Default value with all of the regions to match the default from the dashboard, and found out that this is also not supported for `schema.TypeList` https://github.com/hashicorp/terraform-plugin-sdk/issues/142

As such, I'm sorry to say I run out of ideas here. If you got any tips, happy to reopen the issue & address in a proper way; until then, I'd recommend always setting the regions in the resource specifications explicitly, which will solve the problem for you as well.
