### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by simonrozsival** [BetterStackHQ/terraform-provider-better-uptime#4]
From the [API docs](https://docs.betteruptime.com/api/getting-started)

- [x] Status Pages Sections
- [x] Metadata
- [x] Escalation policies (requires API support first)

------

original issue: https://github.com/BetterStackHQ/deprecated-terraform-provider-betteruptime/issues/5

**Comment by juan-vg** [comment]
New parameter `domain_expiration` for monitor [creation](https://docs.betteruptime.com/api/monitors-api#creating-a-new-monitor) / [update](https://docs.betteruptime.com/api/monitors-api#updating-an-existing-monitor) has been added to API

**Comment by gyfis** [comment]
Update: the latest provider version (0.3.2) has status page sections implemented.

**Comment by juan-vg** [comment]
Support for metadata has been added to API at https://docs.betteruptime.com/api/metadata-api

It can be used for [Monitor, Heartbeat, Incident, WebhookIntegration, EmailIntegration]

PD: Despite it's a separated API endpoint, I believe it would be very useful to integrate this feature to the above resources as an array parameter (like `tags` parameter in other providers such as AWS)

**Comment by gw0** [comment]
Idea to never be behind with API features: If the Terraform provider is just a wrapper for the API, so its code could be mostly auto-generated from the API documentation.

**Comment by mirobertod** [comment]
Any ETA to fully support Escalation policies via API? Currently only GETs are supported (https://docs.betteruptime.com/api/escalation-policies-api)

**Comment by gyfis** [comment]
@mirobertod I don't have a specific ETA, but we're tracking the API high on our engineering plan. I'll keep you posted!

**Comment by fibis** [comment]
When I see it correctly, escalation policies are implemented with the latest release: https://github.com/BetterStackHQ/terraform-provider-better-uptime/releases/tag/v0.3.15

**Comment by gyfis** [comment]
@fibis Hi Adrian, that’s correct, thanks for the ping!

**Comment by PetrHeinz** [comment]
Support for Metadata was already added in [v0.4.0](https://github.com/BetterStackHQ/terraform-provider-better-uptime/releases/tag/v0.4.0) from Nov 22, 2023, closing the issue 🙌
