### ISSUE TITLE
betteruptime_monitor: variable verify_ssl = false should disable ssl_expiration variable

### ISSUE THREAD

**Issue by Edeholland** [BetterStackHQ/terraform-provider-better-uptime#44]
When you have a betteruptime_monitor with `verify_ssl = false` and without setting the `ssl_expiration` variable, you get an error:

> Error: PATCH https://betteruptime.com/api/v2/monitors/xxxxxxx returned 422: {"errors":{"base":["SSL expiration is invalid. Valid values are: [nil, 1, 2, 3, 7, 14, 30, 60]"]}}

Using `verify_ssl = false` should disable the need for the `ssl_expiration` variable. This can be done in more ways than one:

- Set a default value for `ssl_expiration` so you don't always have to set the variable
- Actually configure the API to not require a value for `ssl_expiration`

**Comment by Tatarkow** [comment]
Hello,

William from Better Stack here. I apologise once again for the troubles.

After checking the issue it seems that it is now possible to both create resources with `verify_ssl = false` and modify `verify_ssl` of existing resources to `false`. That said, I noticed a warning message regarding `null` values (including `ssl_expiration`) and legacy Terraform SDK.
![image](https://github.com/BetterStackHQ/terraform-provider-better-uptime/assets/6751346/250e6110-a284-4885-96bb-e79ed0bf8abd)

**Comment by Tatarkow** [comment]
Following my previous message, it looks like the issue has been resolved.
