### ISSUE TITLE
logo_url drift

### ISSUE THREAD

**Issue by sparkacus** [BetterStackHQ/terraform-provider-better-uptime#46]
Creating a status page with a custom logo results in state drift

```
resource "betteruptime_status_page" "example" {
  # other params
  logo_url                   = "https://mydomain.com/logo.png"
```

#terraform plan
```
  ~ resource "betteruptime_status_page" "example" {
        id                         = "123"
      ~ logo_url                   = "https://uptime-storage.s3.amazonaws.com/logos/123.png" -> "https://mydomain.com/logo.png"
    }
```

The only way to get around this is to create a lifecycle rule to ignore the logo_url, but the problem is we genuinely need to update the logo on the odd occasions.

**Comment by curusarn** [comment]
Hi @sparkacus,

Thanks a lot for reporting this. I appreciate it.

I'll add the issue to our internal tracking and I will see to it that it gets solved.

I'll make sure to keep you posted here on GitHub.

Thank you again for raising this.
