### ISSUE TITLE
Email integrations `match_between` has `content_after` and `content_before` mapped out of order?

### ISSUE THREAD

**Issue by mkochco** [BetterStackHQ/terraform-provider-better-uptime#54]
While trying to extract a field using `other_started_fields`

```
other_started_fields {
    content_after = "START_TAG"
    content_before = "END_TAG"
    match_type     = "match_between"
    name           = "TestAttribute"
    field_target   = "body"
}
```

Results in the following

<img width="762" alt="image" src="https://github.com/BetterStackHQ/terraform-provider-better-uptime/assets/1760848/6f4b3672-c1e4-4b01-b459-9203cb74dc2e">

**Comment by adikus** [comment]
@mkochco This is intentional (although perhaps confusing)

* `content_before` - _content_ is _before_ this value
* `content_after` - _content_ is _after_ this value

**Comment by mkochco** [comment]
@adikus Thanks but your description seems to support the case for this being a bug.

In my example I'm looking for `_THIS_` in `START_TAG_THIS_END_TAG`.  

Following the description provided in your comment

- content_before - content is before this value
- content_after - content is after this value

 I would specify 

`content_before = "END_TAG"` and `content_after = "START_TAG"`

Which I believe is what I've done.  Yet the RULE is configured as text `between END_TAG and START_TAG`

**Comment by adikus** [comment]
@mkochco I should rephrase then (this shows that this is a bit confusing even to me - however it is consistent with how it is in the UI - you can check the input names there 🙂).
It should be:
* `content_before` - the content of this attribute can be found before the target value
* `content_after` - the content of this attribute can be found after the target value 

i.e. for you example:
content_before = "START_TAG" and content_after = "END_TAG"

**Comment by mkochco** [comment]
I believe your description still supports that this is a bug.  

If I used your approach we'll be configuring looking for _THIS_START_TAGEND_TAG_THIS_ 

Using your description,

content = _THIS_
target value = START_TAG

"the content of this attribute can be found before the target value" - _THIS_ occurs before START_TAG

target_value = END_TAG

"the content of this attribute can be found after the target value" - _THIS_ occurs after END_TAG

This seems very straight forward, trying to reason about why it should remain in it's current state doesn't make any sense.  It's clearly causing confusion.  So an "as designed" argument seems a bit silly

**Comment by gyfis** [comment]
Hey Mark @mkochco, nice to meet you! This is Tomas, CTO @ Better Stack. Thanks for documenting your thought process - I do appreciate you caring about the integration here!

I agree the naming of the two fields in the terraform provider could be improved to provide more clarity. However, it currently matches what we have in the public API (and in our own implementation powering the Dashboard UI form), so it'd be hard to change without making this a breaking change across the board.

From the POV of the procedure that tries to match the content between other content:

- You want to match text between two other texts/content: START_TAG and END_TAG
- first, find the index of the _content before_ your match: START_TAG
- then, find the index of the _content after_ your match: END_TAG
- finally, slice the original text to only include the text between.

It's possible we still won't agree here, but I wanted to provide more background for the current name.

BTW, thanks for the ping on the other terraform issue, that slipped our tracker altogether 🙏. I'm going to take a look at that immediately.

Let us know if there's anything else, please!
