### ISSUE TITLE
`betteruptime_monitor` accepts different `request_timeout` values depending on the `monitor_type`

### ISSUE THREAD

**Issue by simonrozsival** [BetterStackHQ/terraform-provider-better-uptime#6]
A follow up to [#1 (comment)](https://github.com/BetterStackHQ/deprecated-terraform-provider-betteruptime/pull/1#issuecomment-863595127).

-------
original issue: https://github.com/BetterStackHQ/deprecated-terraform-provider-betteruptime/issues/3

**Comment by adikus** [comment]
Closing this issue for now, since this is somewhat expected. It would be nicer if we could choose a different default value for different monitor types, but the user should be adjust their config based on the given error message.
