### ISSUE TITLE
Support for urgencies for API and Terraform

### ISSUE THREAD

**Issue by Edeholland** [BetterStackHQ/terraform-provider-better-uptime#61]
There currently is no way to configure urgencies through Terraform, this makes working with escalation policies in Terraform less useful. Support for urgencies would greatly improve my workflow.

**Comment by fancybear-dev** [comment]
fixed two weeks ago; https://github.com/BetterStackHQ/terraform-provider-better-uptime/commit/a71e74c060622ec4cd302e831e46f1af2582823f

**Comment by PetrHeinz** [comment]
Hello @Edeholland and @fancybear-dev!

Apologies for not closing this one earlier, it's been already implemented using [Severities API](https://betterstack.com/docs/uptime/api/list-all-severities/) in [v0.8.0](https://github.com/BetterStackHQ/terraform-provider-better-uptime/releases/tag/v0.8.0) 🚀 

Thank you for the idea and the note 🙌
