### ISSUE TITLE
betteruptime_aws_cloudwatch_integration does not support the "paused" attribute

### ISSUE THREAD

**Issue by Gael101** [BetterStackHQ/terraform-provider-better-uptime#66]
As the title states , the betteruptime_aws_cloudwatch_integration does not support to be paused using terraform.

I get the following message when applying configuration.
```
betteruptime_aws_cloudwatch_integration.backups: Modifying... [id=37769]
╷
│ Error: PATCH https://betteruptime.com/api/v2/aws-cloudwatch-integrations/37769 returned 422: {"errors":"Sorry, you misspe
lled some attributes","invalid_attributes":["paused"]}
│ 
│   with betteruptime_aws_cloudwatch_integration.backups,
│   on uptime_integration.tf line 1, in resource "betteruptime_aws_cloudwatch_integration" "backups":
│    1: resource "betteruptime_aws_cloudwatch_integration" "backups" {
│ 
╵
```

**Comment by curusarn** [comment]
Hi @Gael101,

Thank you for raising this.

I'm passing this on to the team to get it fixed. We'll keep you updated here on GitHub.

Thank you for your patience. I appreciate it.

**Comment by curusarn** [comment]
Hi @Gael101,

Thank you for reporting this.

We have released a fix. The problem should now be resolved.
Let me know if the issue persists for you. 🙏

Thanks again for raising this. I appreciate it.
