### ISSUE TITLE
Status page history cannot be set to 30

### ISSUE THREAD

**Issue by Rogdham** [BetterStackHQ/terraform-provider-better-uptime#73]
[`betteruptime_status_page`](https://registry.terraform.io/providers/BetterStackHQ/better-uptime/latest/docs/resources/betteruptime_status_page).`history` has a hard minimum of `90` days, whereas it is possible to set it to 30 days in the web interface:

![web interface](https://github.com/BetterStackHQ/terraform-provider-better-uptime/assets/3994389/559166ae-cfaa-4d53-a8c4-efb25bac12f3)

**Comment by janzhanal** [comment]
Issue for Tatum company as well.
I can do a pull request to fix this.

**Comment by janzhanal** [comment]
It's here:
https://github.com/BetterStackHQ/terraform-provider-better-uptime/blob/0ea73b758e3f88a04962cefd5437fe67c172bf68/internal/provider/resource_status_page.go#L26

internal/provider/resource_status_page.go

```
if history < 90 {
	errs = append(errs, fmt.Errorf("%q must be at least 90, got: %d", key, history))
}
```

**Comment by Shadey212** [comment]
Hi @janzhanal and @Rogdham,

Thanks a lot once again for your report and for your patience with this one; really appreciate it! 🙏 

We went ahead and adjusted the values we allowed for the input. Should now be working as expected from v0.9.1. 👍 

Please let us know if you'd encounter any other issues. ^^
