### ISSUE TITLE
betteruptime_status_page.logo_url drift

### ISSUE THREAD

**Issue by Rogdham** [BetterStackHQ/terraform-provider-better-uptime#74]
Hello, this looks like a follow-up to #46 (ping @JanPokorny).

The following shows on `terraform plan` after a successful `terraform apply`:
```
  ~ resource "betteruptime_status_page" "example" {
        id                         = "123"
      + logo_url                   = "https://example.com/logo.png"
        # (18 unchanged attributes hidden)
    }
```

Moreover, I can see that if I apply again, the URL of the logo on the status page (hosted on `uptime-storage.s3.amazonaws.com`) changes.

---

```
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/betterstackhq/better-uptime v0.7.0
```

**Comment by JanPokorny** [comment]
Hello! I'm afraid I can't help you here since I'm no longer a part of Better Stack

**Comment by PetrHeinz** [comment]
Hello @Rogdham, thank you for reporting this, and for your patience 🙌 

We've fixed the issue with `logo_url` being sent of every `terraform apply`. There's no need to update your Terraform provider, we've managed to fix this on the API level.

Hope this helps 🚀
