### ISSUE TITLE
Logo url of betteruptime_status_page not persitent in state

### ISSUE THREAD

**Issue by fancybear-dev** [BetterStackHQ/terraform-provider-better-uptime#83]
Hi,

Using the betteruptime_status_page resource, when specifying a logo_url value - it keeps reappearing in the plan/apply. I suspect this is a bug where it's not being written to state after apply. Terraform wants to change the resource and add the value - as it thinks it's not currently configured. The change does proceed to be applied and is in effect in Better Stack.

Fixed it for now by using lifecycle policy;

```
lifecycle {
  ignore_changes = [
    logo_url
  ]
}
```

**Comment by fancybear-dev** [comment]
seems to have been reported a while ago; https://github.com/BetterStackHQ/terraform-provider-better-uptime/issues/74

**Comment by PetrHeinz** [comment]
Hello @fancybear-dev, thank you for reporting this, for your patience and sharing a workaround 🙌 

We've fixed the issue with `logo_url` being sent of every `terraform apply`. There's no need to update your Terraform provider, we've managed to fix this on the API level.

Hope this helps 🚀
